"""
api/main.py
============
FastAPI service exposing the review analytics data over REST. This is the
ONLY component the Streamlit dashboard is allowed to talk to — it never
queries MySQL directly.

Run from the project root:
    uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

Interactive docs are auto-generated by FastAPI at /docs (Swagger UI) and
/redoc.
"""

from __future__ import annotations

import logging
import math
from typing import List, Optional

from fastapi import Depends, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import case, func, select
from sqlalchemy.orm import Session

from etl.config import ConfigError, get_settings
from etl.db import check_connection, get_db
from etl.models import EtlRun, Keyword, Review
from etl import extract as extract_stage, load as load_stage, transform as transform_stage
from etl.app_input import InvalidAppIdentifierError, extract_app_id
from api.schemas import (
    AnalyzeAppRequest,
    AnalyzeAppResponse,
    EtlRunOut,
    EtlStatsOut,
    HealthOut,
    KeywordOut,
    PaginatedReviews,
    ReviewOut,
    SentimentTrendPoint,
    SummaryOut,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Review Intelligence API",
    description=(
        "Serves cleaned, sentiment-scored Google Play review data and "
        "ETL run statistics to the analytics dashboard."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup() -> None:
    """Fail fast and loudly if required configuration is missing."""
    try:
        get_settings()
    except ConfigError as exc:
        logger.error("Configuration error at startup: %s", exc)
        raise
    logger.info("API startup complete. Configuration validated.")


# ---------------------------------------------------------------------------
# /health
# ---------------------------------------------------------------------------
@app.get("/health", response_model=HealthOut, tags=["Health"])
def get_health() -> HealthOut:
    """Report API liveness and database connectivity."""
    db_ok = check_connection()
    return HealthOut(status="ok", database="connected" if db_ok else "disconnected")



# ---------------------------------------------------------------------------
# /apps/analyze
# ---------------------------------------------------------------------------
@app.post("/apps/analyze", response_model=AnalyzeAppResponse, tags=["Ingestion"])
def analyze_app(payload: AnalyzeAppRequest) -> AnalyzeAppResponse:    
    try:
        app_id = extract_app_id(payload.input)
    except InvalidAppIdentifierError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    settings = get_settings()

    try:
        raw_df = extract_stage.run_extraction(settings, app_ids=[app_id])
    except Exception:
        logger.exception("Extraction failed for app_id=%s", app_id)
        raise HTTPException(
            status_code=502,
            detail=f"Failed to fetch reviews for '{app_id}' from Google Play.",
        )

    if raw_df.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No reviews were found for app id '{app_id}'. "
                "It may not exist on Google Play, or has no reviews in the "
                "configured language/country."
            ),
        )

    clean_df, keywords_df, stats = transform_stage.transform(raw_df)
    stats["app_ids"] = app_id

    try:
        load_counts = load_stage.load_dataframes([app_id], clean_df, keywords_df, stats)
    except Exception:
        logger.exception("Load failed for app_id=%s", app_id)
        raise HTTPException(
            status_code=500,
            detail="Failed to load the analyzed reviews into the database.",
        )

    return AnalyzeAppResponse(
        app_id=app_id,
        status="SUCCESS",
        raw_count=stats.get("raw_count", 0),
        final_row_count=stats.get("final_row_count", 0),
        new_reviews_inserted=load_counts.get("new_reviews_inserted", 0),
        duplicate_reviews_skipped=load_counts.get("duplicate_reviews_skipped", 0),
        message=(
            f"Analyzed {stats.get('final_row_count', 0)} reviews for {app_id} "
            f"({load_counts.get('new_reviews_inserted', 0)} new)."
        ),
    )


# ---------------------------------------------------------------------------
# /reviews
# ---------------------------------------------------------------------------
_VALID_SORT_FIELDS = {
    "review_date": Review.review_date,
    "rating": Review.rating,
    "sentiment_score": Review.sentiment_score,
    "thumbs_up_count": Review.thumbs_up_count,
}


@app.get("/reviews", response_model=PaginatedReviews, tags=["Reviews"])
def list_reviews(
    page: int = Query(1, ge=1, description="1-indexed page number"),
    page_size: int = Query(20, ge=1, le=200, description="Rows per page"),
    sentiment_label: Optional[str] = Query(
        None, description="Filter by Positive, Neutral, or Negative"
    ),
    rating: Optional[int] = Query(None, ge=1, le=5, description="Exact rating filter"),
    min_rating: Optional[int] = Query(None, ge=1, le=5),
    max_rating: Optional[int] = Query(None, ge=1, le=5),
    app_id: Optional[str] = Query(None, description="Filter by Google Play app id"),
    search: Optional[str] = Query(
        None, description="Free-text search within review text"
    ),
    sort_by: str = Query("review_date", description="One of: " + ", ".join(_VALID_SORT_FIELDS)),
    order: str = Query("desc", pattern="^(asc|desc)$"),
    db: Session = Depends(get_db),
) -> PaginatedReviews:
    """
    Paginated, filterable, sortable review listing. Backs the Review
    Explorer dashboard page.
    """
    if sort_by not in _VALID_SORT_FIELDS:
        raise HTTPException(
            status_code=400,
            detail=f"sort_by must be one of: {', '.join(_VALID_SORT_FIELDS)}",
        )
    if sentiment_label and sentiment_label not in {"Positive", "Neutral", "Negative"}:
        raise HTTPException(
            status_code=400,
            detail="sentiment_label must be one of: Positive, Neutral, Negative",
        )
    if min_rating is not None and max_rating is not None and min_rating > max_rating:
        raise HTTPException(
            status_code=400, detail="min_rating cannot exceed max_rating"
        )

    try:
        query = select(Review)

        if sentiment_label:
            query = query.where(Review.sentiment_label == sentiment_label)
        if rating is not None:
            query = query.where(Review.rating == rating)
        if min_rating is not None:
            query = query.where(Review.rating >= min_rating)
        if max_rating is not None:
            query = query.where(Review.rating <= max_rating)
        if app_id:
            query = query.where(Review.app_id == app_id)
        if search:
            query = query.where(Review.review_text.ilike(f"%{search}%"))

        count_query = select(func.count()).select_from(query.subquery())
        total = db.execute(count_query).scalar_one()

        sort_column = _VALID_SORT_FIELDS[sort_by]
        sort_column = sort_column.desc() if order == "desc" else sort_column.asc()
        query = query.order_by(sort_column)

        query = query.offset((page - 1) * page_size).limit(page_size)
        rows = db.execute(query).scalars().all()

        total_pages = math.ceil(total / page_size) if total else 0

        return PaginatedReviews(
            total=total,
            page=page,
            page_size=page_size,
            total_pages=total_pages,
            items=[ReviewOut.model_validate(r) for r in rows],
        )
    except HTTPException:
        raise
    except Exception:
        logger.exception("Failed to list reviews.")
        raise HTTPException(status_code=500, detail="Failed to retrieve reviews.")


# ---------------------------------------------------------------------------
# /sentiment-trend
# ---------------------------------------------------------------------------
@app.get(
    "/sentiment-trend", response_model=List[SentimentTrendPoint], tags=["Analytics"]
)
def get_sentiment_trend(
    app_id: Optional[str] = Query(None, description="Filter by Google Play app id"),
    db: Session = Depends(get_db),
) -> List[SentimentTrendPoint]:
    """Daily positive/neutral/negative review counts. Backs trend charts."""
    try:
        day_expr = func.date(Review.review_date)
        query = (
            select(
                day_expr.label("day"),
                func.sum(case((Review.sentiment_label == "Positive", 1), else_=0)).label(
                    "positive"
                ),
                func.sum(case((Review.sentiment_label == "Neutral", 1), else_=0)).label(
                    "neutral"
                ),
                func.sum(case((Review.sentiment_label == "Negative", 1), else_=0)).label(
                    "negative"
                ),
            )
            .group_by(day_expr)
            .order_by(day_expr)
        )
        if app_id:
            query = query.where(Review.app_id == app_id)

        rows = db.execute(query).all()
        return [
            SentimentTrendPoint(
                date=row.day, positive=row.positive, neutral=row.neutral, negative=row.negative
            )
            for row in rows
        ]
    except Exception:
        logger.exception("Failed to compute sentiment trend.")
        raise HTTPException(status_code=500, detail="Failed to compute sentiment trend.")


# ---------------------------------------------------------------------------
# /top-keywords
# ---------------------------------------------------------------------------
@app.get("/top-keywords", response_model=List[KeywordOut], tags=["Analytics"])
def get_top_keywords(
    sentiment_label: Optional[str] = Query(
        None, description="Positive, Neutral, or Negative. Omit for all."
    ),
    app_id: Optional[str] = Query(None, description="Filter by Google Play app id"),
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
) -> List[KeywordOut]:
    """Top keywords by cumulative frequency. Backs Keyword Intelligence page."""
    if sentiment_label and sentiment_label not in {"Positive", "Neutral", "Negative"}:
        raise HTTPException(
            status_code=400,
            detail="sentiment_label must be one of: Positive, Neutral, Negative",
        )
    try:
        query = select(Keyword)
        if sentiment_label:
            query = query.where(Keyword.sentiment_label == sentiment_label)
        if app_id:
            query = query.where(Keyword.app_id == app_id)
        query = query.order_by(Keyword.frequency.desc()).limit(limit)

        rows = db.execute(query).scalars().all()
        return [KeywordOut(keyword=r.keyword, frequency=r.frequency) for r in rows]
    except HTTPException:
        raise
    except Exception:
        logger.exception("Failed to retrieve top keywords.")
        raise HTTPException(status_code=500, detail="Failed to retrieve top keywords.")


# ---------------------------------------------------------------------------
# /summary
# ---------------------------------------------------------------------------
@app.get("/summary", response_model=SummaryOut, tags=["Analytics"])
def get_summary(
    app_id: Optional[str] = Query(None, description="Filter by Google Play app id"),
    db: Session = Depends(get_db),
) -> SummaryOut:
    """Headline KPIs. Backs the Executive Overview page."""
    try:
        query = select(
            func.count().label("total"),
            func.avg(Review.rating).label("avg_rating"),
            func.sum(case((Review.sentiment_label == "Positive", 1), else_=0)).label("pos"),
            func.sum(case((Review.sentiment_label == "Neutral", 1), else_=0)).label("neu"),
            func.sum(case((Review.sentiment_label == "Negative", 1), else_=0)).label("neg"),
        )
        if app_id:
            query = query.where(Review.app_id == app_id)

        row = db.execute(query).one()
        total = row.total or 0

        if total == 0:
            return SummaryOut(
                total_reviews=0,
                average_rating=0.0,
                positive_count=0,
                neutral_count=0,
                negative_count=0,
                positive_pct=0.0,
                neutral_pct=0.0,
                negative_pct=0.0,
            )

        pos, neu, neg = row.pos or 0, row.neu or 0, row.neg or 0
        return SummaryOut(
            total_reviews=total,
            average_rating=round(float(row.avg_rating or 0.0), 2),
            positive_count=pos,
            neutral_count=neu,
            negative_count=neg,
            positive_pct=round(100 * pos / total, 2),
            neutral_pct=round(100 * neu / total, 2),
            negative_pct=round(100 * neg / total, 2),
        )
    except Exception:
        logger.exception("Failed to compute summary.")
        raise HTTPException(status_code=500, detail="Failed to compute summary.")


# ---------------------------------------------------------------------------
# /etl-stats
# ---------------------------------------------------------------------------
@app.get("/etl-stats", response_model=EtlStatsOut, tags=["Data Quality"])
def get_etl_stats(
    history: int = Query(10, ge=1, le=100, description="Number of recent runs to return"),
    db: Session = Depends(get_db),
) -> EtlStatsOut:
    """Latest + recent ETL run statistics. Backs the Data Quality page."""
    try:
        query = select(EtlRun).order_by(EtlRun.run_timestamp.desc()).limit(history)
        rows = db.execute(query).scalars().all()
        runs = [EtlRunOut.model_validate(r) for r in rows]
        return EtlStatsOut(latest_run=runs[0] if runs else None, recent_runs=runs)
    except Exception:
        logger.exception("Failed to retrieve ETL stats.")
        raise HTTPException(status_code=500, detail="Failed to retrieve ETL stats.")